import { Course, Instructor, FAQItem, Transaction, Student, Certificate, Activity, Agenda } from "./types";

export const LOGO_URL =
  "https://image2url.com/r2/default/images/1770479630100-8df01458-b375-4198-ae0e-4b1762b1ada7.png";

export const MOCK_INSTRUCTORS: Instructor[] = [
  {
    id: "kusnadi-ikhwani",
    name: "Ustadz Kusnadi Ikhwani",
    role: "Praktisi Kemasjidan",
    bio: "Praktisi pengelolaan masjid dan penguatan peran marbot dalam operasional harian.",
    avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8W3r-ZBxfd50TD8Ho9cSBowOqhAQuL2Y63g&s",
    rating: 4.8,
    totalCourses: 4,
    totalStudents: 2300,
    location: "Sragen",
  },
  {
    id: "haidar-muhammad",
    name: "Ustadz Haidar Muhammad",
    role: "Takmir & Manajemen Masjid",
    bio: "Berpengalaman dalam manajemen masjid, penguatan layanan jamaah, dan tata kelola masjid modern.",
    avatar:
      "https://static.republika.co.id/uploads/images/headline_slide/sektretaris-umum-takmir-masjid-jogokaryan-ustaz-haidar-muhammad_231125092349-624.jpg",
    rating: 4.9,
    totalCourses: 5,
    totalStudents: 4100,
    location: "Jogokaryan, Yogyakarta",
  },
  {
    id: "abdul-somad",
    name: "Ustadz Abdul Somad",
    role: "Pengajar & Dai",
    bio: "Menyampaikan materi keislaman dan motivasi pengabdian masjid secara mudah dan membumi.",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT99qAcwhSDEUMmxHHzjEfna9YVgtg-04A8rDvXbaNtZf-70ZkRxFPl_i5J_he-DnfdtO7EhS0ouUaiu-hq_bE8Ni9U3xKBjsAdFgzAg4w&s=10",
    rating: 4.9,
    totalCourses: 3,
    totalStudents: 10000,
    location: "Riau",
  },
  {
    id: "salim-fillah",
    name: "Ustad Salim A. Fillah",
    role: "Inspirator & Pendidikan Islam",
    bio: "Fokus pada penguatan nilai, adab, dan peran masjid sebagai pusat peradaban.",
    avatar: "https://proumedia.co.id/wp-content/uploads/2022/05/1-Salim-A-Fillah.jpeg",
    rating: 4.8,
    totalCourses: 4,
    totalStudents: 6500,
    location: "Yogyakarta",
  },
  {
    id: "1",
    name: "Ust. Ahmad Fauzi",
    role: "Praktisi Kemasjidan",
    bio: "Berpengalaman mengelola 3 masjid besar di Jakarta dengan sistem manajemen modern.",
    avatar: "https://picsum.photos/seed/i1/200/200",
    rating: 4.9,
    totalCourses: 5,
    totalStudents: 1200,
    location: "Jakarta",
  },
  {
    id: "2",
    name: "H. Bambang S.",
    role: "Takmir & Manajemen",
    bio: "Spesialis operasional masjid dan pemberdayaan ekonomi jamaah.",
    avatar: "https://picsum.photos/seed/i2/200/200",
    rating: 4.8,
    totalCourses: 8,
    totalStudents: 2500,
    location: "Surabaya",
  },
];

export const MOCK_COURSES: Course[] = [
  {
    id: "c1",
    title: "Standar Operasional Kebersihan Masjid",
    level: "Pemula",
    rating: 4.8,
    students: 3400,
    duration: "2 jam",
    modules: 8,
    instructor: MOCK_INSTRUCTORS[0],
    price: "Gratis",
    thumbnail: "https://picsum.photos/seed/c1/400/250",
    category: "Kebersihan",
    description: "Pelajari cara menjaga masjid tetap wangi, rapi, and nyaman untuk jamaah 24 jam.",
    lastUpdate: "Januari 2024",
    status: "Published",
  },
  {
    id: "c2",
    title: "Manajemen Keuangan Masjid yang Transparan",
    level: "Menengah",
    rating: 4.9,
    students: 1200,
    duration: "4 jam",
    modules: 12,
    instructor: MOCK_INSTRUCTORS[1],
    price: "Rp 49.000",
    thumbnail: "https://picsum.photos/seed/c2/400/250",
    category: "Manajemen",
    description: "Membangun kepercayaan jamaah melalui laporan keuangan yang terbuka and akurat.",
    lastUpdate: "Februari 2024",
    status: "Published",
  },
  {
    id: "c3",
    title: "Teknik Dasar Pengeras Suara (Audio) Masjid",
    level: "Pemula",
    rating: 4.7,
    students: 850,
    duration: "1.5 jam",
    modules: 6,
    instructor: MOCK_INSTRUCTORS[2],
    price: "Gratis",
    thumbnail: "https://picsum.photos/seed/c3/400/250",
    category: "Teknis",
    description: "Setting audio mixer and microphone agar suara adzan and kajian jernih.",
    lastUpdate: "Desember 2023",
    status: "Published",
  },
  {
    id: "c4",
    title: "Adab dan Pelayanan Prima Jamaah Masjid",
    level: "Pemula",
    rating: 5.0,
    students: 2100,
    duration: "2 jam",
    modules: 5,
    instructor: MOCK_INSTRUCTORS[3],
    price: "Gratis",
    thumbnail: "https://picsum.photos/seed/c4/400/250",
    category: "Layanan",
    description: "Bagaimana menyambut tamu Allah dengan senyum, salam, and sapa yang tepat.",
    lastUpdate: "Maret 2024",
    status: "Published",
  },
  {
    id: "c5",
    title: "Digital Marketing untuk Syiar Masjid",
    level: "Menengah",
    rating: 4.6,
    students: 600,
    duration: "5 jam",
    modules: 15,
    instructor: MOCK_INSTRUCTORS[4],
    price: "Rp 75.000",
    thumbnail: "https://picsum.photos/seed/c5/400/250",
    category: "Manajemen",
    description: "Mengoptimalkan sosial media and website masjid untuk jangkauan yang lebih luas.",
    lastUpdate: "Maret 2024",
    status: "Draft",
  },
  {
    id: "c6",
    title: "Manajemen Inventaris dan Aset Masjid",
    level: "Pemula",
    rating: 4.8,
    students: 450,
    duration: "1 jam",
    modules: 4,
    instructor: MOCK_INSTRUCTORS[0],
    price: "Gratis",
    thumbnail: "https://picsum.photos/seed/c6/400/250",
    category: "Teknis",
    description: "Cara mendata and merawat barang wakaf agar tidak cepat rusak atau hilang.",
    lastUpdate: "April 2024",
    status: "Published",
  },
];

export const MOCK_AGENDA: Agenda[] = [
  {
    id: "a1",
    slug: "standar-kebersihan-sanitasi-masjid",
    title: "Standar Kebersihan & Sanitasi Masjid",
    type: "Offline",
    date: "20 Feb 2026",
    time: "08:00",
    endTime: "12:00",
    location: "Masjid Jogokaryan, Yogyakarta",
    locationName: "Yogyakarta",
    price: "Gratis",
    priceNum: 0,
    quota: 100,
    remainingQuota: 15,
    description: "Workshop praktik langsung teknik pembersihan and sanitasi area masjid agar nyaman bagi jamaah.",
    narasumber: "Ustadz Kusnadi Ikhwani",
    cover: "https://picsum.photos/seed/a1/800/450",
    status: "Published",
    registrantsCount: 85,
  },
  {
    id: "a2",
    slug: "manajemen-inventaris-masjid-sistem",
    title: "Manajemen Inventaris Masjid dengan Sistem",
    type: "Online",
    date: "28 Feb 2026",
    time: "19:30",
    endTime: "21:30",
    location: "https://zoom.us/j/dummy-link",
    locationName: "Zoom Cloud Meeting",
    price: "Rp 50.000",
    priceNum: 50000,
    quota: 300,
    remainingQuota: 120,
    description: "Pelatihan digitalisasi pendataan aset masjid untuk mencegah kehilangan and mempermudah perawatan.",
    narasumber: "Ustadz Haidar Muhammad",
    cover: "https://picsum.photos/seed/a2/800/450",
    status: "Published",
    registrantsCount: 180,
  },
  {
    id: "a3",
    slug: "pelayanan-jamaah-adab-petugas",
    title: "Pelayanan Jamaah & Adab Petugas Masjid",
    type: "Offline",
    date: "05 Mar 2026",
    time: "09:00",
    endTime: "15:00",
    location: "Grand Asy-Syakirin, Solo",
    locationName: "Solo",
    price: "Rp 75.000",
    priceNum: 75000,
    quota: 150,
    remainingQuota: 45,
    description: "Meningkatkan hospitality pengurus masjid dalam menyambut and melayani jamaah dengan adab yang baik.",
    narasumber: "Ust Salim A. Fillah",
    cover: "https://picsum.photos/seed/a3/800/450",
    status: "Published",
    registrantsCount: 105,
  },
  {
    id: "a4",
    slug: "teknis-sound-system-masjid-petugas",
    title: "Teknis Sound System Masjid untuk Petugas",
    type: "Online",
    date: "12 Mar 2026",
    time: "20:00",
    endTime: "22:00",
    location: "https://meet.google.com/dummy-link",
    locationName: "Google Meet",
    price: "Gratis",
    priceNum: 0,
    quota: 500,
    remainingQuota: 210,
    description: "Panduan teknis setting audio agar suara adzan and kajian terdengar jelas tanpa feedback.",
    narasumber: "Ir. Hendra Wijaya",
    cover: "https://picsum.photos/seed/a4/800/450",
    status: "Published",
    registrantsCount: 290,
  },
  {
    id: "a5",
    slug: "workshop-tata-kelola-takmir-modern",
    title: "Workshop Tata Kelola Takmir Modern",
    type: "Offline",
    date: "20 Mar 2026",
    time: "08:00",
    endTime: "17:00",
    location: "Masjid Istiqlal, Jakarta",
    locationName: "Jakarta",
    price: "Gratis",
    priceNum: 0,
    quota: 200,
    remainingQuota: 10,
    description: "Pelatihan kepemimpinan and manajemen organisasi bagi pengurus takmir masjid di era digital.",
    narasumber: "Ustadz Abdul Somad",
    cover: "https://picsum.photos/seed/a5/800/450",
    status: "Published",
    registrantsCount: 190,
  },
  {
    id: "a6",
    slug: "strategi-syiar-digital-untuk-masjid",
    title: "Strategi Syiar Digital untuk Masjid",
    type: "Online",
    date: "27 Mar 2026",
    time: "19:30",
    endTime: "21:30",
    location: "https://zoom.us/j/dummy-link-2",
    locationName: "Zoom Cloud Meeting",
    price: "Rp 60.000",
    priceNum: 60000,
    quota: 400,
    remainingQuota: 155,
    description:
      "Bagaimana memanfaatkan platform media sosial untuk menyebarkan syiar and informasi masjid secara luas.",
    narasumber: "Ust. Ahmad Fauzi",
    cover: "https://picsum.photos/seed/a6/800/450",
    status: "Published",
    registrantsCount: 245,
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: "s1",
    name: "Budi Santoso",
    email: "budi@mail.com",
    phone: "081234567890",
    coursesJoined: 3,
    progress: 65,
    status: "Aktif",
    joinDate: "12 Jan 2024",
  },
  {
    id: "s2",
    name: "Ani Wijaya",
    email: "ani@mail.com",
    phone: "081234567891",
    coursesJoined: 1,
    progress: 100,
    status: "Aktif",
    joinDate: "15 Jan 2024",
  },
  {
    id: "s3",
    name: "Fahmi Idris",
    email: "fahmi@mail.com",
    phone: "081234567892",
    coursesJoined: 5,
    progress: 20,
    status: "Aktif",
    joinDate: "20 Jan 2024",
  },
  {
    id: "s4",
    name: "Siti Aminah",
    email: "siti@mail.com",
    phone: "081234567893",
    coursesJoined: 2,
    progress: 45,
    status: "Aktif",
    joinDate: "22 Jan 2024",
  },
  {
    id: "s5",
    name: "Rahmat Hidayat",
    email: "rahmat@mail.com",
    phone: "081234567894",
    coursesJoined: 1,
    progress: 10,
    status: "Nonaktif",
    joinDate: "01 Feb 2024",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    invoice: "INV/20240220/001",
    userName: "Budi Santoso",
    courseTitle: "Manajemen Keuangan Masjid",
    amount: "Rp 49.000",
    method: "Gopay",
    status: "Berhasil",
    date: "20 Feb 2024",
  },
  {
    id: "t2",
    invoice: "INV/20240220/002",
    userName: "Fahmi Idris",
    courseTitle: "Digital Marketing Syiar",
    amount: "Rp 75.000",
    method: "OVO",
    status: "Berhasil",
    date: "20 Feb 2024",
  },
];

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: "cert1",
    studentName: "Ani Wijaya",
    courseTitle: "Standar Operasional Kebersihan Masjid",
    certNumber: "MARBOT/CERT/2024/001",
    issueDate: "20 Jan 2024",
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  { id: "a1", type: "course", title: 'Kursus "Digital Marketing Syiar" dipublish', timestamp: "2 jam yang lalu" },
  { id: "a2", type: "transaction", title: "Transaksi baru: Budi Santoso (Rp 49.000)", timestamp: "3 jam yang lalu" },
  { id: "a3", type: "student", title: "Peserta baru bergabung: Ani Wijaya", timestamp: "5 jam yang lalu" },
  { id: "a4", type: "instructor", title: "Pengajar baru ditambahkan: Ust. Ahmad Fauzi", timestamp: "1 hari yang lalu" },
];

export const FAQS: FAQItem[] = [
  {
    question: "Apakah ini untuk marbot saja?",
    answer:
      "Tidak, Marbot LMS dirancang untuk seluruh pengurus masjid (Takmir), remaja masjid, relawan, hingga staf operasional masjid.",
  },
  {
    question: "Apakah ada sertifikat?",
    answer:
      "Ya, setiap kursus yang diselesaikan akan memberikan sertifikat digital yang bisa diunduh langsung dari profil Anda.",
  },
  {
    question: "Materi bisa diakses lewat HP?",
    answer:
      "Tentu! Platform kami sepenuhnya responsif and dapat diakses melalui browser di HP maupun tablet Anda kapan saja.",
  },
  {
    question: "Bagaimana cara daftar?",
    answer: 'Klik tombol "Daftar" di kanan atas, masukkan data diri Anda, and Anda bisa langsung mulai belajar.',
  },
  {
    question: "Apakah kursus berbayar?",
    answer:
      "Tersedia kursus gratis (didukung donatur) and kursus berbayar untuk materi yang lebih mendalam and spesifik.",
  },
  {
    question: "Siapa yang menyusun materi?",
    answer:
      "Materi disusun oleh praktisi kemasjidan, takmir berpengalaman, and trainer profesional di bidangnya masing-masing.",
  },
];
