import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";

import fontInter from "@/configs/font-inter";

import { Providers } from "./providers";

import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
      </head>
      <body className={`${fontInter.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
